### ISSUE TITLE
can't build locally

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/ocs3#544]
The build fails for me with:

```
[error] org.scalajs.testcommon.RPCCore$RPCException
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:69)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:67)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:47)
[error] 	at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[error] 	at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:47)
[error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: $g.WebSocket is not a constructor
[error] 	at <jscode>.eval(webpack:///./seqexec_web_client-test-fastopt.js?:4144)
[error] 	at scala.scalajs.runtime.AnonFunction0.apply(webpack:///./seqexec_web_client-test-fastopt.js?:121517)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary$lzycompute(webpack:///./seqexec_web_client-test-fastopt.js?:128520)
[error] 	at org.scalacheck.ArbitraryLowPriority$$anon$1.arbitrary(webpack:///./seqexec_web_client-test-fastopt.js?:128516)
[error] 	at org.scalacheck.Prop$.forAll(webpack:///./seqexec_web_client-test-fastopt.js?:97583)
[error] 	at cats.kernel.laws.discipline.EqTests.eqv(webpack:///./seqexec_web_client-test-fastopt.js?:7405)
[error] 	at seqexec.web.client.ModelSpec.<init>(webpack:///./seqexec_web_client-test-fastopt.js?:257373)
[error] 	at <jscode>.$c_Lseqexec_web_client_ModelSpec.$e.seqexec.web.client.ModelSpec(webpack:///./seqexec_web_client-test-fastopt.js?:258136)
[error] 	at <jscode>.$newJSObjectWithVarargs(webpack:///./seqexec_web_client-test-fastopt.js?:478)
[error] 	at org.scalajs.testinterface.TestUtils$.newInstance(webpack:///./seqexec_web_client-test-fastopt.js?:23821)
```

What do I need to set up locally to make this work? We need to document it in the README.

**Comment by cquiroz** [comment]
I think you need to install jsdom. Try doing this at the ocs3 dir:

`npm install jsdom`

And note what version do you get. This was on the readme but it was probably taken away in the merge

**Comment by tpolecat** [comment]
```
ocs3 (json)$ npm install jsdom
npm WARN saveError ENOENT: no such file or directory, open '/Users/rnorris/Scala/ocs3/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/rnorris/Scala/ocs3/package.json'
npm WARN ocs3 No description
npm WARN ocs3 No repository field.
npm WARN ocs3 No README data
npm WARN ocs3 No license field.

+ jsdom@11.11.0
added 94 packages in 4.789s
```

**Comment by cquiroz** [comment]
Did the installation of jsdom let you do the full build?

**Comment by sraaphorst** [comment]
We should probably clear these out. @tpolecat ?
